apiVersion: v1
kind: Service
metadata:
  name: planet9-sidecar-poc
spec:
  ports:
    - port: 80
  selector:
    app: planet9
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet9-sidecar-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: planet9
  template:
    metadata:
      labels:
        app: planet9
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: planet9
          image: neptunesoftware/planet9:v2.0.4
          resources:
            requests:
              cpu: 100m
              memory: 0.6Gi
            limits:
              cpu: 200m
              memory: 0.6Gi
          ports:
            - containerPort: 8080
              name: planet9
        - name: planet9-sidecar
          image: iansegers/sidecar:v3
          ports:
            - containerPort: 3000
              name: planet9-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: p9-sidecare-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: p9-sidecare-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io